### PR TITLE
Test fixes for recent JUnit and Java versions

### PR DESCRIPTION
**Pull request by chewi**
Apologies for this necrophilic pull request but Gentoo still needs to build this from source in order to build things like Jython and we ideally like to have the tests pass. A new release would be nice but unlikely, I suppose. Hope it helps someone anyway.

### CODE REVIEW

**Comment by parrt** [comment]
thanks! can you sign the contributors.txt file for me?

**Comment by chewi** [comment]
What contributors.txt file? :wink: If it helps, I'm really not fussed about the credit.

**Comment by parrt** [comment]
https://github.com/antlr/stringtemplate4/blob/master/contributors.txt

it's how i guarantee clean license :)

**Comment by chewi** [comment]
Right but that is v4 and this is v3.

**Comment by parrt** [comment]
oh crap. ur right. sorry.

**Pull request merged**
